#!/bin/bash

runCommand()
{
    if [ "$1" == "mpirun" ]; then sol="$4"; else sol="$1"; fi
    sol=$(basename -- "$sol")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

# Unset and source bashrc
if [ -f "/opt/openfoam7/etc/config/unset.sh" ]; then  # for OF < 4
   source "/opt/openfoam7/etc/config/unset.sh" 2> /dev/null
else
   source "/opt/openfoam7/etc/config.sh/unset" 2> /dev/null
fi
source "/opt/openfoam7/etc/bashrc"

runCommand blockMesh
runCommand surfaceFeatureExtract

runCommand snappyHexMesh -overwrite

runCommand surfaceToPatch "constant/triSurface/Body001_Geometry.stl"

if [ ! -z $FOAM_API ] && [ $FOAM_API -ge 1906 ]
then
    runCommand surfaceMeshExtract mesh_outside.stl
else
    runCommand surfaceMeshTriangulate mesh_outside.stl
fi

runCommand surfaceTransformPoints -scale "(1000 1000 1000)" mesh_outside.stl mesh_outside.stl
